### ISSUE TITLE
[Bug]:Link not working in thirdparty 

### ISSUE THREAD

**Issue by secretkontributer** [OpenChemistry/openchemistry#128]
When you go in third party 
![Screenshot 2024-01-05 232000](https://github.com/OpenChemistry/openchemistry/assets/134409422/2cffe598-7a16-4d70-b758-b4c29b6f12f8)

**Try to open qttesting  the page is not found.**
![Screenshot 2024-01-05 232129](https://github.com/OpenChemistry/openchemistry/assets/134409422/ca0aa646-350e-41da-b572-513ad0782980)

![Screenshot 2024-01-05 232229](https://github.com/OpenChemistry/openchemistry/assets/134409422/4de37cc0-cf88-42ce-a673-1b088dc75f5f)

**Comment by ghutchis** [comment]
This is not a bug. The submodule points to https://gitlab.kitware.com/paraview/qttesting

If you want to complain to GitHub, feel free. But it seems a conscious decision to not link to GitLab.
