### ISSUE TITLE
zlib linking error (?)

### ISSUE THREAD

**Issue by 1ykos** [OpenChemistry/openchemistry#26]
when running obabel after a fresh pull and make I get many errors of the kind:
`*** Open Babel Error  in openLib
  /home/usr/bin/openchemistry/prefix/lib/openbabel/smilesformat.so did not load properly.
 Error: /home/usr/bin/openchemistry/prefix/lib/libz.so.1: version 'ZLIB_1.2.9' not found (required by /usr/lib64/libpng16.so.16)`
I will attempt to compile against system libraries.

**Comment by cryos** [comment]
I haven't see that, but it looks like a conflict between the system PNG library, and the built zlib. Switching to system would likely help, I will try and take a look at that, it is strange that smilesformat would like to that too.

**Comment by 1ykos** [comment]
could you help me out? When I run
`ccmake openchemistry`
and then configure it to use system libraries
`make *`
produces only empty directories. I am probably missing something trivial there...

**Comment by cryos** [comment]
ccmake or cmake-gui will let you edit the cache. For ccmake you normally need two configure (c) and one generate (g) before exiting. Then if you are using makefiles you should be able to run make. The directories will be empty until they are built, you should see output for building each external project.

**Comment by 1ykos** [comment]
Thx, I was missing the (g) I think.

**Comment by 1ykos** [comment]
Ok this fixed it, I can run geometry optimization when compiling with system zlib.
