### ISSUE TITLE
Update third party dependencies

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/openchemistry#3]
They haven't been updated in some time, verify they work on Windows, Mac and Linux. Ideally update them all to be compatible with Visual Studio 2015, El Capitan, etc.

**Comment by cryos** [comment]
PR #4 has some updates, I will test these out on Windows, and merge them if they work (or make them conditional otherwise).

**Comment by barrymoo** [comment]
I want to make some notes here about my experiences with the current third party modules.

- System PCRE is still not supported (it's small so I don't mind, plus it compiles every time I test)
- Building VTK with multiple Qt versions installed is obnoxious. Specifying CMAKE_PREFIX_PATH to a specific Qt installation's cmake directories will mix-and-match Qt versions. It would be nice to make this more transparent for a user. There may be a VTK cmake variable I need to specify?
- MongoDB build fails on Mac (downloads file: `thirdparty/mongodb-prefix/src/mongodb/src/mongo/platform/unordered_map.h` which doesn't look for correct include on Mac, I copied the file from the newest version of mongodb and that works as a temporary fix). I imagine upgrading will fix this issue.
- ChemKit was last touched 4 years ago. It doesn't appear to be in active development, should/can we remove it?

**Comment by cryos** [comment]
I have a branch I need to finish up. I might turn off MongoChem by default which will remove the need for MongoDB, ChemKit, PCRE, etc (all required, but just this one app that many aren't interested in). I would like to keep it, but it has the most challenging dependencies and the least activity. I am out on travel, but let me try and take a look at that solution on the weekend.

VTK should be finding Qt 5, I have not hit issues but will see about a fresh build on the Mac to verify. It is possible I missed something, and I want to move VTK forward as things were improved recently for Qt 5. Thanks for the notes.

**Comment by cryos** [comment]
Short-term - just type,

make -j5 avogadroapp

It will not build things not needed by Avogadro 2.

**Comment by barrymoo** [comment]
I can get around the issue, but I am thinking long term.

**Comment by barrymoo** [comment]
Actually, Molequeue won't build if I have conda-qt (I imagine this is used by a lot of people) installed.

Relevant outputs from: `make -j4 avogadroapp`

`CMAKE_PREFIX_PATH` points to downloaded Qt5.

Conda Qt Installed: http://pastebin.com/7MTBnqJf
Conda Qt Removed: http://pastebin.com/sUnxs2se

I will test to see if this happens on my Arch machine.

**Comment by ghutchis** [comment]
Can we revisit? It seems as if MongoChem isn't advancing much. It'd be great to have, but I think it's holding back development of Avo2.

**Comment by cryos** [comment]
Not sure how it is holding it back, but I can turn it off by default so that most people can ignore it.

**Comment by cryos** [comment]
I think #10 addresses the concerns of MongoChem holding back development, it can certainly be removed in future if we don't move it forward further.

**Comment by cryos** [comment]
I want to keep this open, I think most of this has been addressed, but want to try a full clean default build to see if everything works well on the major platforms. I can open up another, but I really want to get the latest Windows build working with VS2015 for C++11, new community edition, and other features. It is mainly an issue with third-party packages as far as I can tell.

**Comment by cryos** [comment]
I am going to close this, I just got everything compiling on VS2015, updated a number of dependencies. I will test other platforms, but hopefully people like the more minimal build. I think for a normal build I have eliminated a number of dependencies that were causing issues. You shouldn't need Boost, HDF5, and any of the stuff MongoChem pulled in.
