### ISSUE TITLE
Version bumps for third party libraries

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/openchemistry#31]
* zlib - was 1.2.8 now 1.2.11 - security fixes
* libxml2 - was now 2.9.7 - security fixes 
* pcre - was 8.34 - 
* Eigen - was 3.2.8, now 3.3.4
* Boost - was 1.60, now 1.66
* Glew - was 1.13 now 2.1.0
* hdf5 now 1.10.2
* spglib - now 1.10.1
* libarchive - was 3.2.2 now 3.3.2 

Possible things to drop:
* Chemkit? (I don't see any dependencies in the code itself..)
* pcre?
* kdsoap?

**Comment by cryos** [comment]
I have been wanting to drop Boost too, only needed by non-C++11 and Chemkit. The kdsoap is optional, but would like to keep for builds of MoleQueue that use SOAP. I would also like to verify the best Windows compiler - Visual Studio 2015 versus 2017. This will be affected by what compilers our dependencies support.

**Comment by ghutchis** [comment]
Is Chemkit still needed? If so, for what? (Maybe we can replace it with RDKit.)

**Comment by cryos** [comment]
No, I wasn't suggesting we keep Chemkit. I will remove at least Chemkit and Boost. The libxml2 is primarily for Open Babel - in fact do we need Boost for Open Babel too, or it is fine without?

**Comment by ghutchis** [comment]
Open Babel doesn't need Boost for a modern compiler.

**Comment by cryos** [comment]
I have done a few of the removals

- Boost
- ChemKit
- PCRE
- MongoDB client
- MongoChem

I bumped GLEW, zlib had compilation issues on Windows, as did libxml2 when I last bumped them. I will take a look at them on my Windows system tomorrow as I want to bump to MSVC 2017 (at least 2015) where things have changed quite a bit. We can merge now, or I can work through some of the others and get them tested.

**Comment by cryos** [comment]
I verified everything compiles and seems to run on Windows with VS2017! I upgraded a few more packages including libxml2, zlib, and eigen in the branch. There are some issues in HDF5 I need to look into, and didn't get to spglib or libarchive yet.

**Comment by cryos** [comment]
The spglib library seems to have changed, missing symbol issues. I think I will skip that, but the rest work on Linux and Windows.

**Comment by ghutchis** [comment]
I'll check on spglib - but I suspect togo might not consider API changes as problems. Let's set that as a separate issue / pull request.

**Comment by cryos** [comment]
That is unfortunate, it is a separate pull request. If there is no API stability then we may not want to update all that frequently. Possibly waiting until there are new features/fixes we know we need. I think I updated all other dependencies (or removed them). So this can probably be closed.
