### ISSUE TITLE
mongochem submodule mapping issue

### ISSUE THREAD

**Issue by dlf57** [OpenChemistry/openchemistry#37]
Upon cloning openchemistry I am met with 
```
fatal: no submodule mapping found in .gitmodules for path 'mongochem'
```
I saw that there was some spring cleaning recently and mongochem was removed from .gitmodules as well as .git/config. Running ```git rm --cached mongochem``` seemed to fix it and allow me to build just fine.

**Comment by cryos** [comment]
Thanks for pointing this out, don't delete submodules often and had missed a step.
