### ISSUE TITLE
problem in building openchemistry: cmake cannot download files while wget works.

### ISSUE THREAD

**Issue by hopefulp** [OpenChemistry/openchemistry#44]
Would you help me to solve building issue?
I have followed the wiki and cmake version is 3.6.1 in CentOS 7.5.

how to download the external files in cmake? cmake cannot download.
The below is some extraction of error message.

downloading...
       src='http://www.openchemistry.org/files/tpl/eigen-3.3.4.tar.gz'
error: downloading 'http://www.openchemistry.org/files/tpl/eigen-3.3.4.tar.gz' failed
LOG BEGIN ---
    Trying 66.194.253.19...
Connected to www.openchemistry.org (66.194.253.19) port 80 (#0)
GET /files/tpl/eigen-3.3.4.tar.gz HTTP/1.1
Host: www.openchemistry.org
User-Agent: curl/7.44.0
Accept: */*
HTTP/1.1 302 Found
Date: Wed, 08 Aug 2018 04:29:57 GMT
Server: Apache
Location: https://openchemistry.org/files/tpl/eigen-3.3.4.tar.gz
Connection #0 to host www.openchemistry.org left intact
Issue another request to this URL: 'https://openchemistry.org/files/tpl/eigen-3.3.4.tar.gz'
Protocol "https" not supported or disabled in libcurl

Returning to my statement,
all the downloaded files have size=0.

I can download those files manually, but after installation, I cannot find "online database" which is shown in youtube. I am afraid that this is related to the disconnection shown in installation process.

how can I fix the cmake download problem?

**Comment by ghutchis** [comment]
We have now switched away from storing files on openchemistry.org - this should work.

Not sure what "online  database" you mention, but please submit any follow-up questions to https://discuss.avogadro.cc/
